version: '2.0'
services:
  server:
    build:
      context: ./demo.graphql
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  client:
    build:
      context: ./demo.react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"